### ISSUE TITLE
Submit button is rendered twice

### ISSUE THREAD

**Issue by sallyx** [instante/bootstrap3renderer#10]
```php
   public function createComponetSearch() {
     $renderer = new BootstrapRenderer;
     $form = new \Nette\Application\UI\Form;
     $form->setRenderer($renderer);
     $form->addGroup('Group name:');
    //$form->addText('q','');
     $form->addSubmit('submit','Search');
     return $form;
   }
```

latte: `{control search}`

Form is rendered with two Search submit buttons, one top, one bottom.
If  setGroupsRenderedFirst() is called on $renderer, submit button is rendered twice bottom.

Tested on Nette 2.4, bootstrap3renderer 2.0.0

**Comment by richard-ejem** [comment]
It should be fixed now.

**Comment by sallyx** [comment]
It works! Thanks!
