### ISSUE TITLE
missing class form-control with manual rendering

### ISSUE THREAD

**Issue by sallyx** [instante/bootstrap3renderer#12]
If i render form like this in latte: `{control form}`, inputs get class="form-conrtol".
But if i render it like this: `{form form}{input xxx}{/form} the class is missing.

**Comment by richard-ejem** [comment]
You probably did not register the `Instante\ExtendedFormMacros\DI\ExtendedFormMacrosExtension` extension - sorry, it was hidden deep in docs, I put it to the beginning of [documentation](https://github.com/instante/bootstrap3renderer/blob/master/docs/index.md) now.

**Comment by sallyx** [comment]
Thanks, ithis helped.
