### ISSUE TITLE
Manaul rendering of RadioList not working

### ISSUE THREAD

**Issue by martenb** [instante/bootstrap3renderer#17]
When I try to manual render RadioList, it ends with Notice "Undefined index: $key"
```latte
{foreach $form['delivery']->items as $key=>$val}
    {input delivery:$key}
{/foreach}
```

**Comment by richard-ejem** [comment]
It was actually an issue of the related package https://github.com/instante/extended-form-macros , fixed in last release.
Don't forget to clean Latte cache after update :)
