### ISSUE TITLE
end() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by simPod** [instante/bootstrap3renderer#2]
Nette 2.4 says:
User Deprecated

Nette\Bridges\FormsLatte\FormMacros::renderFormBegin() is deprecated, use Nette\Bridges\FormsLatte\Runtime::renderFormBegin()

tried to fix it but was not successful

**Comment by simPod** [comment]
or actually I did but another error came out right away. Does this work with nette 2.4 or not?

see https://github.com/instante/bootstrap3renderer/pull/3

this error is weird though
![image](https://cloud.githubusercontent.com/assets/327717/16268804/135a8ce6-3890-11e6-858e-fc19c6d94a0b.png)

**Comment by richard-ejem** [comment]
Thanks for report. Looks like you just redirected the class alias FormMacros to Runtime, that would not work - FormMacros and Runtime are two different classes, where Runtime class (appeared in Nette 2.4) has just renderFormBegin and renderFormEnd methods. Try to fix it like I suggested in comment on your pull request, or I'll look at it maybe later.

**Comment by simPod** [comment]
it started working with nette upgrade :) no modifications required. thanks

**Comment by simPod** [comment]
Ok I was wrong. I had error in my code and Bootstrap renderer haven't been called. The error is still there. Investigating further

**Comment by simPod** [comment]
https://github.com/instante/bootstrap3renderer/pull/4
