### ISSUE TITLE
Add 'Did you mean' help message for wrong class

### ISSUE THREAD

**Issue by honzagula** [instante/bootstrap3renderer#7]
Instead of Exception 'No instanceof Nette\Forms\Form found in local scope' we can show something more user friendly.

**Comment by richard-ejem** [comment]
@honzagula this is related to 1.x only and occurs because of bad design of latte macro implementation. It is solved in 2.0 and I don't think it is serious enough as an improvement of 1.x version, we'd rather focus to improve 2.0 and release as stable soon :)

**Comment by honzagula** [comment]
I agree. Closing.
